name: create release pr

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pr-note:
    name: pr-note
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install pr-note
      - run: >
          pr-note
          --owner K-tecchan
          --repo pr-note
          --base release
          --head main
          --template-path .github/release-template.tera
          --group-by title
        env:
          PR_NOTE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
